### ISSUE TITLE
MaxPerSpawnWave

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#10]
**Is your feature request related to a problem? Please describe.**
I don't see anyway other to have a class spawn for every wave and take only one personne to be this class at 100%. Ex: I want a Chaos leader in every wave. 

**Describe the solution you'd like**
Adding the parameters "MaxPerSpawnWave" would let me have unlimited of MaxAlive and be sure to have the class selected with each spawn wave since I could keep the high ChanceToGet.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by steven4547466** [comment]
This isn't a perfect way, but until the next version this will work as a rudimentary system. I will add this suggestion in the next release (1.2.0)

Set:
`MaxAlive: 1`
and:
`ChanceToGet: 100`
and:
`GivenOnEscape: false`

This will make the max alive at any time to 1 (this is the part that makes this system a temporary way because then it cant spawn every wave if another is alive) and will always give it, but not on escape.

**Comment by steven4547466** [comment]
[Prerelease 1.2.0 1](https://github.com/steven4547466/AdvancedSubclassing/releases/tag/1.2.0-pre001) should add this (it is untested as of writing this)
