### ISSUE TITLE
MapEvent Overriding

### ISSUE THREAD

**Issue by aurelienblais** [steven4547466/AdvancedSubclassing#27]
**Describe the bug**
Using latest `pre` version, when a plugin add an event listener to `MapEvents.ExplodingGrenade`, the event won't be triggered by a frag grenade.

**To Reproduce**
1. Bind an event to `MapEvents.ExplodingGrenade`
2. Do something, like logging "Something exploded"
3. Throw a frag grenade in game, nothing will log, try with a flash and it'll work

**Expected behavior**
Don't break event binding

**Versioning**
 - AdvancedSubclassing Version (1.2.0-pre007):

**Comment by steven4547466** [comment]
I made no changes to my patches for grenades in that version. I also use that event myself [here](https://github.com/steven4547466/AdvancedSubclassing/blob/master/Handlers/Map.cs#L12)... I'll look into it when I get time to see if my plugin actually causes this issue.

Edit: Yeah, this is a bug, I'll see what I can do to fix it. Exiled's exploding grenade event is pretty wack though...

**Comment by steven4547466** [comment]
This will be fixed in the next release, I'm gonna be honest, idk who made the ExplodingGrenadeEvent for exiled, but that's some of the weirdest code I've seen lol.

**Comment by steven4547466** [comment]
Should be fixed [here](https://github.com/steven4547466/AdvancedSubclassing/releases/tag/1.2.0-pre008) (I literally just call the event, I still need this because setting `IsAllowed` to false still breaks windows and doors, which that patch fixes). Let me know if you experience any weird behavior, or it doesn't work after this.

I already reported the door and glass break bug to exiled, should be getting fixed soon enough, then I'll delete the patch entirely.
